global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['10.0.10.97:32300', '10.0.29.194:32300']

  - job_name: 'sensor-api'
    static_configs:
      - targets: ['10.0.10.97:32224', '10.0.29.194:32224']

  - job_name: 'cadvisor'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /etc/prometheus/token
    kubernetes_sd_configs:
      - role: node
        kubeconfig_file: /etc/prometheus/kubeconfig
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: 10.0.2.156:6443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['10.0.1.11:9104']
        labels:
          instance_name: db_registry

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.0.10.97:9100']
        labels:
          instance_name: node1
      - targets: ['10.0.29.194:9100']
        labels:
          instance_name: node2
      - targets: ['10.0.2.156:9100']
        labels:
          instance_name: control-plane
      - targets: ['10.0.1.11:9100']
        labels:
          instance_name: db_registry
      - targets: ['10.0.26.75:9100']
        labels:
          instance_name: monitoring
